### ISSUE TITLE
Release of v3.0

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#31]
We are looking forward to release _Babykarte v3.0_ on first advent (01.12.2019). But before we can do that we need to do the following:

- [x] Translating help text into english #30 
  - [x] Re-checking 
- [x] Preparing privacy policy for translation into french #11 
- [x] Translating privacy policy into french #11 
- [x] Converting privacy policies into HTML
- [x] Translating _Babykarte v3.0_ into french
- [x] Removing old outcommented code
- [x] Releasing _Babykarte v3.0_, informing community
- [x] Adding backend support for relations for opening in OSM (release independent)

**Comment by ValorNaram** [comment]
@NicolasGrosjean Could you also please translate the new parts in file `js/fr.js`?

As usual the changed parts are marked with a `(EN)` at the end of every string so you just have to search those.

**Comment by ValorNaram** [comment]
@NicolasGrosjean Don't you have write access to our repository?

**Comment by Discostu36** [comment]
Only to the old one. Fixed now @NicolasGrosjean

**Comment by ValorNaram** [comment]
@Discostu36 It's your turn, prepare the text for tomorrow.
