### ISSUE TITLE
Modern JS

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte#51]
I want to get rid of

- JQuery

and want to change the code to my new coding style in Javascript, HTML, CSS

## Tasks

- [ ] Change Javascript requests to the new fetch() API
- [ ] Getting rid of JQuery
- [ ] Check, if the remove of JQuery needs changes in our Privacy Policy and if so make this changes
